service: 'ruby-on-lambda-example-a'

provider:
  name: aws
  runtime: ruby2.5
  memorySize: 128
  stage: skudo
  region: eu-central-1

functions:
  test:
    handler: handlers.show
    events:
      - http:
          path: /test
          method: get
          cors: true
